Sil\Bundle\UomBundle\Entity\UomType:
    type:                            mappedSuperclass
    table:                           sil_uom_type
    fields:
        name:
            type:                    string(64)
            unique:                  true
            nullable:                false

    oneToMany:
        uoms:
          targetEntity:              Sil\Bundle\UomBundle\Entity\Uom
          mappedBy:                  type
