services:

    ###################
    # FORM TYPES
    ###################

    sil.form_type.uom_qty:
        class: Sil\Bundle\UomBundle\Form\Type\UomQtyFormType
        tags:
            - {name: form.type, alias: form}
        arguments:
            - '@sil.repository.uom'
